"""
commit 1_12_25
1) Implementacion de MVC
2) POO
3) Interfaces:
    3.1 menu_principales()
    3.2 menu_acciones()
    3.3 insertar_autos()
    3.4 consultar_autos()
    3.5 cambiar_autos()
    3.6 borrar_autos()

commit_3_12_25
1) Interfaces:
    1.1 insertar_camionetas()
    1.2 consultar_camionetas()
    2.3 cambiar_camionetas()
    1.4 borrar_camionetas()
    2.1 insertar_camiones()
    2.2 consultar_camiones()
    2.3 cambiar_camiones()
    2.4 borrar_camiones()

commit_4_12_25
1) Controlador:
    1.1 menu_principal()
    1.2 menu_acciones()
    1.3 insertar_autos()
    1.4 consultar_autos()
    1.5 cambiar_autos()
    1.6 borrar_autos()

commit_5_12_25
1) Controlador:
    1.1 insertar_camiones()
    1.2 consultar_camiones()
    1.3 cambiar_camiones()
    1.4 borrar_camiones()

Productos Entregables:
**Interaccion con la funcionalidad (Controlador) de las interfaces anteriores
**nombre del commit: "commit_05_12_25"

"""